Repository UMM-CSci-3601/3601-iteration-template, pull requests merged in 2024-01, with the labels that each got.

#1355 Update Gradle wrapper to latest version of Gradle (v8.5)
  server/gradle/wrapper/gradle-wrapper.properties
  server/settings.gradle
Labels: dependencies, java, priority - looking for approval

#1389 Remove JDK8 dependencies
  server/build.gradle
Labels: good first issue, dependencies, java, priority - looking for approval

#1366 Improve the `UserController` test coverage
  server/src/main/java/umm3601/user/UserController.java
  server/src/test/java/umm3601/user/UserControllerSpec.java
Labels: enhancement, javascript

#1369 Improve add user component coverage
  client/src/app/users/add-user.component.spec.ts
  client/src/app/users/add-user.component.ts
  client/src/app/users/user.service.spec.ts
Labels: enhancement, javascript

#1397 Refactor `Server#main`
  server/build.gradle
  server/src/main/java/umm3601/Controller.java
  server/src/main/java/umm3601/Main.java
  server/src/main/java/umm3601/Server.java
  server/src/main/java/umm3601/user/UserController.java
Labels: help wanted, question, java

#1425 Update CodeQL config
  .github/workflows/codeql.yml
Labels: enhancement

#1432 1417 switch from ngmodule to standalone
  client/src/app/app.component.spec.ts
  client/src/app/app.component.ts
  client/src/app/app.module.ts
  client/src/app/home/home.component.spec.ts
  client/src/app/home/home.component.ts
  client/src/app/users/add-user.component.spec.ts
  client/src/app/users/add-user.component.ts
  client/src/app/users/user-card.component.spec.ts
  client/src/app/users/user-card.component.ts
  client/src/app/users/user-list.component.spec.ts
  client/src/app/users/user-list.component.ts
  client/src/app/users/user-profile.component.spec.ts
  client/src/app/users/user-profile.component.ts
  client/src/main.ts
Labels: enhancement, javascript

#1442 Improve error handling when failing to load a user profile
  client/src/app/users/user-profile.component.html
  client/src/app/users/user-profile.component.scss
  client/src/app/users/user-profile.component.spec.ts
  client/src/app/users/user-profile.component.ts
Labels: bug, javascript

#1454 Update to the new Angular control flow
  client/src/app/users/add-user.component.html
  client/src/app/users/add-user.component.ts
  client/src/app/users/user-card.component.html
  client/src/app/users/user-card.component.ts
  client/src/app/users/user-list.component.html
  client/src/app/users/user-list.component.ts
  client/src/app/users/user-profile.component.ts
Labels: enhancement, javascript

#1441 Improve user card design
  .github/workflows/client.yaml
  .github/workflows/codeql.yml
  .github/workflows/e2e.yaml
  .github/workflows/server.yml
  client/src/app/users/user-card.component.html
  client/src/app/users/user-card.component.scss
  client/src/app/users/user-card.component.ts
Labels: enhancement, javascript

#1461 Replace long string appends with multi-line strings
  server/src/test/java/umm3601/user/UserControllerSpec.java
Labels: enhancement, java
